# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_auto_20170920_1949'),
        ('authentication', '0026_auto_20171108_1027'),
    ]

    operations = [
    ]
